defaults:
  - model@params: base
  - loss@params: base
  - override hydra/sweeper: optuna
  - _self_

hydra:
  run:
    dir: ../outputs/${settings.job_type[0]}/${now:%Y-%m-%d_%H-%M-%S}
  job_logging:
    formatters:
      simple:
        format: '[%(levelname)s][%(name)s] - %(message)s'
  sweep:
    dir: ../multirun/${settings.job_type[0]}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    study_name: train
    direction: minimize
    n_jobs: 1
    n_trials: 20
    search_space:
      params.lr:
        type: float
        low: 1e-6
        high: 1e-3
        log: True
      params.min_lr:
        type: float
        low: 1e-7
        high: 1e-5
        log: True
      params.weight_decay:
        type: float
        low: 1e-7
        high: 1e-5
        log: True
      params.gradient_acc_step:
        type: categorical
        choices:
          - 1
          - 2
          - 3
          - 4
      params.max_grad_norm:
        type: categorical
        choices:
          - 0.1
          - 1
          - 10
          - 1000

mlflow:
  enabled: False
  tracking_uri: http://127.0.0.1:5000
  experiment: sugi-petfinder2

wandb:
  enabled: True
  entity: imokuri
  project: petfinder2-1
  dir: ${hydra:runtime.cwd}/../cache/wandb

settings:
  print_freq: 100
  gpus: "4,5,6,7"

  dirs:
    working: ${hydra:runtime.cwd}
    input: ${hydra:runtime.cwd}/../input/petfinder-pawpularity-score/
    train_image: ${settings.dirs.input}train/
    test_image: ${settings.dirs.input}test/

  job_type:
    # - preprocess
    - train
    # - train2
    # - train3
    # - validate
    # - inference

  debug: False
  n_debug_data: 2000

  amp: True
  multi_gpu: True

  n_class: 1

params:
  seed: 440
  n_fold: 10
  epoch: 5
  es_patience: 0
  batch_size: 24
  gradient_acc_step: 1
  max_grad_norm: 1000

validate:
  base_results:
    - swin_large_patch4_window12_384_in22k-v16
    - dm_nfnet_f3-v0
    - dm_nfnet_f4-v0
    - dm_nfnet_f5-v0
    - dm_nfnet_f6-v0
