hydra:
  job_logging:
    formatters:
      simple:
        format: '[%(levelname)s] - %(message)s'

mlflow:
  tracking_uri: http://127.0.0.1:5000
  experiment: sugi-demo-2

settings:
  gpus: "1,2,3,4,5,6,7"
  output_dir: ./
  n_class: 1

params:
  seed: 440
  n_fold: 10
  epoch: 10
  batch_size: 64
  features:
    - mixup
    - cutmix
